version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: factly
      POSTGRES_PASSWORD: qwertyui
      POSTGRES_DB: factly

    ports:
      - "5432:5432"
  server:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    links:
      - "db"
